// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paokwepntsnpkttydkmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhb2t3ZXBudHNucGt0dHlka21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MDg3MTgsImV4cCI6MjA1MjA4NDcxOH0.mzsJFFUsXxSkWlQ6npFjqGb5S-YW8jxY9LqL4vR31cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);